### ISSUE TITLE
疑问？

### ISSUE THREAD

**Issue by leshalv** [aliyun/alibabacloud-console-components#10]
请问这是刚刚开始开源吗？后期会持续维护吗？breezr  我看是内部构建工具，后期有开源计划吗？

**Comment by csr632** [comment]
1. 这个项目是最近才开源的。
2. 这个项目在内部已经使用了很久，现在开源出来，是为了更好地服务于生态伙伴，让他们也能轻松地开发阿里云管控应用。阿里云内部、外部对它有很强的使用需求，当然要持续维护。
3. breezr[已经开源](https://github.com/aliyun/alibabacloud-console-toolkit)，但是目前文档还比较简单。breezr同样是很多阿里云控制台正在使用的构建工具。
