### ISSUE TITLE
中文内容不会自动根据内容调整列宽度，但是英文内容可以

### ISSUE THREAD

**Issue by KevinKingKong** [aliyun/alibabacloud-console-components#17]
import React from 'react'
import { Table } from '@alicloud/console-components'

const dataSource = () => {
  const result = []
  for (let i = 0; i < 5; i++) {
    result.push({
      title: {
        name: `aaa ${3 + i}.0 你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国你好中国`,
      },
      id: 100306660940 + i,
      time: 200000000000000000000 + i,
    })
  }
  return result
}
const render = (value, index, record) => {
  return <a href="javascript:;">Remove({record.id})</a>
}

const Demo1 = () => (
  <Table dataSource={dataSource()} isZebra>
    <Table.Column title="Id" dataIndex="id" />
    <Table.Column title="我爱你" dataIndex="title.name" />
        <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />

    <Table.Column title="Time" dataIndex="time" />
    <Table.Column cell={render} />
  </Table>
)

export default Demo1

[中文内容demo地址](https://m7zdc.csb.app/)

import React from "react";
import { Table } from "@alicloud/console-components";

const dataSource = () => {
  const result = [];
  for (let i = 0; i < 5; i++) {
    result.push({
      title: {
        name: `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ${3 +
          i}.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
      },
      id: 100306660940 + i,
      time: 200000000000000000000 + i
    });
  }
  return result;
};
const render = (value, index, record) => {
  return <a href="javascript:;">Remove({record.id})</a>;
};

const Demo1 = () => (
  <Table dataSource={dataSource()} isZebra>
    <Table.Column title="Id" dataIndex="id" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />
    <Table.Column title="我爱你" dataIndex="title.name" />

    <Table.Column title="Time" dataIndex="time" />
    <Table.Column cell={render} />
  </Table>
);

export default Demo1;

[英文内容demo地址](https://xjukd.csb.app/)

**Comment by csr632** [comment]
`aaaaaa..aaaaa`里面没有空格，所以浏览器不会插入换行。而浏览器乐意在任何中文之间插入换行。

结果就是，英文版的由于没有换行，它的内容宽度超过了容器宽度。
中文版的，通过插入换行，使得容器能够容纳内容。
你可以通过浏览器工具查看这两个demo里面的元素。
