### ISSUE TITLE
下拉列表级联选择后无法动态清除内容

### ISSUE THREAD

**Issue by KevinKingKong** [aliyun/alibabacloud-console-components#18]
省份选择Zhejiang 城市会切换到hangzhou，但选择hubei后，城市下拉列表仍然展示hangzhou，参考fussion，选择省份后清除城市， setCityData([])，但没有效果。

[demo地址：](https://9y9v3.csb.app/)

fusion下拉列表级联没有问题：https://fusion-demo.alibaba-inc.com/demos/next/select

import React, { useState, useCallback } from 'react'
import { Select } from '@alicloud/console-components'
import styled from 'styled-components'

const provinceDataSource = ['Zhejiang', 'Hubei', 'Jiangsu']
const cityDataSource = {
  Zhejiang: ['Hangzhou', 'Ningbo', 'Wenzhou'],
  Hubei: ['Wuhan', 'Yichang', 'Jingzhou'],
  Jiangsu: ['Nanjing', 'Suzhou', 'Zhenjiang'],
}

const SWrapper = styled.div`
  background-color: #f8f8f8;
  padding: 16px;
  .next-select {
    margin-right: 10px;
  }
`

const Demo5 = () => {
  const [cityData, setCityData] = useState([])
  const [province, setProvince] = useState(undefined)
  const [city, setCity] = useState(undefined)
  const [disabled, setDisabled] = useState(true)

  const handleProvinceChange = useCallback(value => {
    const cities = cityDataSource[value]
    setCityData([])
    setCityData(cities)
    setProvince(value)
    setDisabled(!cities)
  }, [])

  const handleCityChange = useCallback(value => {
    setCity(value)
  }, [])

  return (
    <SWrapper>
      <Select
        placeholder="Select Province"
        dataSource={provinceDataSource}
        value={province}
        onChange={handleProvinceChange}
      />
      <Select
        placeholder="Select City"
        dataSource={cityData}
        value={city}
        onChange={handleCityChange}
        disabled={disabled}
      />
    </SWrapper>
  )
}
export default Demo5

**Comment by csr632** [comment]
demo里面加一行即可：
![image](https://user-images.githubusercontent.com/18747423/70764413-80b50880-1d92-11ea-91b8-5640188f3413.png)


你你还可以看看[级联选择组件](https://aliyun.github.io/alibabacloud-console-components/base-components/cascader-select)是否符合你的需求。

**Comment by KevinKingKong** [comment]
这个可以，谢谢
