### ISSUE TITLE
如何使用路由

### ISSUE THREAD

**Issue by wangfeng7399** [aliyun/alibabacloud-console-components#41]
请问如何使用applayout和路由系统？有没有案例？谢谢

**Comment by csr632** [comment]
console-components只是组件库、物料库，用户可以自主选择路由方案，比如你可以使用dva或者react-router-dom，如果是阿里云控制台开发的话，可以使用xconsole。

applayout也只是一个UI组件，有没有路由都能工作，用法查看文档里的demo。
